### ISSUE TITLE
 Exception in thread "Thread-4" java.lang.NullPointerException

### ISSUE THREAD

**Issue by charles-typ** [OpenNetworkingFoundation/DELTA#43]
After running  a test, i encountered a problem and the test couldn't be done.
It looks like:
```javascript
Command> Exception in thread "Thread-4" java.lang.NullPointerException
	at org.deltaproject.manager.core.ChannelAgentManager.write(ChannelAgentManager.java:60)
	at org.deltaproject.manager.testcase.TestAdvancedCase.testSwitchTableFlooding(TestAdvancedCase.java:352)
	at org.deltaproject.manager.testcase.TestAdvancedCase.replayKnownAttack(TestAdvancedCase.java:88)
	at org.deltaproject.manager.core.AttackConductor.executeTestCase(AttackConductor.java:133)
	at org.deltaproject.webui.TestCaseExecutor.run(TestCaseExecutor.java:40)
^CControl-C caught. Removing all log files...
```
Could anyone please help me! Thanks!

**Comment by vieangry** [comment]
Maybe you can try "apt-get install psmisc" in container.
